DEFAULT:
  perform_check: yes  # should the check be performed?
  allowed_licenses:
    - Espressif Modified MIT
    - Espressif-Modified-MIT
    # - Apache-2.0
    # - Unlicense OR CC0-1.0
  license_for_new_files: Espressif Modified MIT
  espressif_copyright_full: |
     /*
      * {license} License
      *
      * Copyright (c) {year} Espressif Systems (Shanghai) CO., LTD
      *
      * Permission is hereby granted for use EXCLUSIVELY with Espressif Systems products.
      * This includes the right to use, copy, modify, merge, publish, distribute, and sublicense
      * the Software, subject to the following conditions:
      *
      * 1. This Software MUST BE USED IN CONJUNCTION WITH ESPRESSIF SYSTEMS PRODUCTS.
      * 2. The above copyright notice and this permission notice shall be included in all copies
      *    or substantial portions of the Software.
      * 3. Redistribution of the Software in source or binary form FOR USE WITH NON-ESPRESSIF PRODUCTS
      *    is strictly prohibited.
      *
      * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
      * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
      * PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
      * FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
      * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
      * DEALINGS IN THE SOFTWARE.
      *
      * SPDX-License-Identifier: LicenseRef-Espressif-Modified-MIT
      */
  espressif_copyright_short: |
    /*
     * SPDX-FileCopyrightText: {year} Espressif Systems (Shanghai) CO., LTD
     * SPDX-License-Identifier: LicenseRef-Espressif-Modified-MIT
     *
     * See LICENSE file for details.
     */

# You can create your own rules for files or group of files
examples_and_test_apps:
  include:
   - '**/examples/basic_examples/**'
   - '**/test_apps/**'
  allowed_licenses:
    - Apache-2.0
  license_for_new_files: Apache-2.0
  espressif_copyright_full: |
    /*
     * SPDX-FileCopyrightText: {year} Espressif Systems (Shanghai) CO., LTD
     *
     * SPDX-License-Identifier: {license}
     */
  espressif_copyright_short: ''

ignore:  # You can also select ignoring files here
  perform_check: no  # Don't check files from that block
  include:
    - '**/esp_gmf_queue.h'
    - '**/managed_components/**'
    - '**/build/**'
    - '**/examples/esp_audio_simple_player/test_apps/main/aud_simp_player_test.c'
    - '**/examples/esp_audio_simple_player/test_apps/main/test_main.c'
    - '**/gmf_core/test_apps/main/cases/gmf_uri_test.c'
    - '**/gmf_core/test_apps/main/test_gmf_core_main.c'
    - '**/gmf_elements/test_apps/main/test_gmf_core_main.c'
    - '**/memory_checks.h'
    - '**/test_utils.h'
    - '**/memory_checks.c'
    - '**/leak_test.c'
    - '**/test_runner.c'
    - '**/test_utils.c'
